### ISSUE TITLE
Entering a point (.) makes the app crash.

### ISSUE THREAD

**Issue by CosmicSausage** [chrisvasqm/android-down#27]
Fix the issue with parsing the input so when the user enters a decimal number without pressing 0 first, the app doesn't crash.

**Comment by chrisvasqm** [comment]
Great, thanks. Is it happening on both input fields or just one?

**Comment by chrisvasqm** [comment]
Thanks for your feedback @CosmicSausage 👍 . This will be fixed on the next update.
